### ISSUE TITLE
Picker remains selected after clicked outside

### ISSUE THREAD

**Issue by mtilokani** [ankurk91/vue-flatpickr-component#2] opened 2017-06-22 11:45 UTC
@ankurk91 As we are opening a picker to select a date and if we are not selecting a date and clicks outside, in this case datepicker remains as selected (focused).

And due to this, we need to click outside again to make it unselected.

Is there any solution for this ?

**Comment by ankurk91** [comment] 2017-06-22 11:47
@mtilokani 
What is your flatpicker version ?

**Comment by mtilokani** [comment] 2017-06-22 11:49
@ankurk91 2.6.3

**Comment by ankurk91** [comment] 2017-06-22 11:49
Please update to v3.0, it was fixed.

**Comment by mtilokani** [comment] 2017-06-22 11:54
@ankurk91 It is not allowing me to install like below:

npm install vue-flatpickr-component@3.0 --save

Its showing below error:
....
npm ERR! notarget No compatible version found: vue-flatpickr-component@3.0
....

**Comment by ankurk91** [comment] 2017-06-22 11:55
I meant v3.0 of flatpickr
```
npm install flatpickr@3
```

**Comment by mtilokani** [comment] 2017-06-22 12:29
@ankurk91 actually I don't difference.

But how can I make it work through vue-flatpickr-component?

Please help me out.

**Comment by ankurk91** [comment] 2017-06-22 12:37
**vue-flatpickr-component** is just wrapper on flatpickr.
when you run 
```
npm install vue-flatpickr-component
```
Its should also install flatpickr v3.x, you can see the dependency [here](https://github.com/ankurk91/vue-flatpickr-component/blob/master/package.json#L30)

**Comment by mtilokani** [comment] 2017-06-22 12:54
Hi @ankurk91 ,

vue-flatpickr-component is got installed with flatpickr 3.0.5 version. Following was the message at console after installation.

├── UNMET PEER DEPENDENCY vue@2.2.6
└─┬ vue-flatpickr-component@1.2.2
  └── flatpickr@3.0.5

But sill I am facing same issue.

**Comment by ankurk91** [comment] 2017-06-22 13:00
I can not look into your current environment and build system.
All i can do is share this working demo with you -
https://plnkr.co/edit/Drp9PAvXgp0NmrEpvMCB?p=preview
As you can see flatpickr v3.0.5 is working fine. 
Datepicker will close when click outside.

**Comment by ankurk91** [comment] 2017-06-22 13:49
Closing because i don't see any real issue with package, feel free to re-open

**Closed by ankurk91** 2017-06-22 13:49 UTC

**Comment by mtilokani** [comment] 2017-06-23 05:34
Hi @ankurk91 ,

In package.json, it is written like below:

"dependencies": {
    "flatpickr": "^2.6.0 || ^3.0.5"
  },

And while installing this package it picks version "2.6.*".
That's why I am facing this issue.

Can you please let me know why it is not picking version "3.0.5" while installing this package.

Thanks.

**Comment by ankurk91** [comment] 2017-06-23 05:36
What is your npm version ?
```
npm --version
```
npm v3.x is buggy i would suggest to use v4.6.x

**Comment by mtilokani** [comment] 2017-06-23 05:37
npm version is 3.10.9

**Comment by mtilokani** [comment] 2017-06-23 05:40
@ankurk91 , npm version is 3.10.9, if I will upgrade to v4.6.*, then it will work, right?

**Comment by mtilokani** [comment] 2017-06-23 05:41
@ankurk91 also if any solution to make this package work with 3.10.9, then please let me know

**Comment by ankurk91** [comment] 2017-06-23 05:42
```
npm install flatpickr@3 --save
```
Thats it

**Comment by mtilokani** [comment] 2017-06-23 05:50
Hi @ankurk91 ,

Yes, but the problem is if I am installing like below:

"npm install vue-flatpickr-component --save"

then it creates a folder as "vue-flatpickr-component" in node modules and inside "vue-flatpickr-component", it creates a flatpickr folder whose version is 2.6.*.

And this is the version that "vue-flatpickr-component" picks.

And if I am installing like you said "npm install flatpickr@3 --save" then it is creating folder "flatpickr" inside node modules, but it is of no mean as "vue-flatpickr-component" picks flatpickr that is inside its folder.

Got my issue?

**Comment by ankurk91** [comment] 2017-06-23 05:58
I downgrade my npm to 3.10.9.

Then i tried -
```
mkdir v-test
cd v-test
npm cache clean -f
npm init -y
npm install vue-flatpickr-component --save
```
I got this error -
```
npm ERR! Linux 4.4.0-57-generic
npm ERR! argv "/home/ankurk/.nvm/versions/node/v6.10.2/bin/node" "/home/ankurk/.nvm/versions/node/v6.10.2/bin/npm" "install" "vue-flatpickr-component" "--save"
npm ERR! node v6.10.2
npm ERR! npm  v3.10.9
npm ERR! code EREADFILE

npm ERR! Error extracting /home/ankurk/.npm/flatpickr/2.6.3/package.tgz archive: ENOENT: no such file or directory, open '/home/ankurk/.npm/flatpickr/2.6.3/package.tgz'
npm ERR! 
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>

npm ERR! Please include the following file with any support request:
npm ERR!     /home/ankurk/projects/v-test/npm-debug.log
```
I am unable to reproduce the issue.

Ultimately it is npm fault not mine.
I am using [right](https://docs.npmjs.com/files/package.json#dependencies) syntax to define dependency versions.

**Comment by mtilokani** [comment] 2017-06-23 06:00
@ankurk91 , yes you are right.

Even I am also getting this same above error.
So its npm fault right?

**Comment by ankurk91** [comment] 2017-06-23 06:01
Yes because it works fine with npm v4.6.1

**Comment by mtilokani** [comment] 2017-06-23 06:15
@ankurk91 , again I installed like below:

"npm install vue-flatpickr-component --save"

and it successfully installed.
You can see screen shot. I am not getting why flatpickr not picking 3.* version.

![error](https://user-images.githubusercontent.com/20898692/27468772-740619d6-5809-11e7-9468-4c0581c49fc2.png)

**Comment by mtilokani** [comment] 2017-06-23 06:20
@ankurk91 , it is written like it has installed 3.* version, but it has not actually installed, it is installing 2.6.*.

**Comment by mtilokani** [comment] 2017-06-23 06:38
@ankurk91 and as it is not installing flatpickr 3.* , that's why I am facing this issue.

**Comment by mtilokani** [comment] 2017-06-23 06:40
And other thing, I am saying picker remains selected/focused when clicked outside. I am not saying that picker doesn't get closed when clicked outside.

When clicked outside without selecting date then picker close, but I find selection/focus on text field.

**Comment by ankurk91** [comment] 2017-06-23 07:56
As said this issue is related to [flatpickr](https://chmln.github.io/flatpickr/) v2.6 itself.
It was resolved in v3.x.
I can not help you anymore.
