### ISSUE TITLE
[8.x] Incorrect date time display

### ISSUE THREAD

**Issue by huypxgear** [ankurk91/vue-flatpickr-component#251] opened 2022-03-04 10:58 UTC
```
[x] Bug report => search github for a similar issue or PR before submitting
[ ] Feature request
[ ] Other, please describe
```

* flatPickr version : 4.6.9
* Vue.js version : 2.6.12
* Browser name and version : Chrome
* This package version : 8.1.7

**Current behavior**
When I set up the date-time value is "01/02, 20:00" 01 February but the Flatpick displays the wrong time. 
Flatpick displays the wrong time
Here is my config 
```js
 monthConfig: {
        dateFormat: 'm/d, H:i',
        enableTime: true,
        time_24hr: true,
      }
```

date time value `"01/02, 20:00"`

Result 
![image](https://user-images.githubusercontent.com/45187933/156750976-3f054eb2-1cb0-4e44-b035-aee601cf4f1c.png)

Reproduction 
https://codesandbox.io/s/serene-cherry-hmqicb?file=/src/components/HelloWorld.vue

**Comment by ankurk91** [comment] 2022-03-04 11:00
Create a minimal reproduction on jsfiddle.net or codesandbox

**Comment by huypxgear** [comment] 2022-03-04 11:48
@ankurk91
I have updated the reproduction link. My flatpick config is based on another variable.

**Comment by ankurk91** [comment] 2022-03-04 11:53
Please remove all those extra code, for example watch for "visible", setTimeout from mounted, 2 different configs,

Keep it simple

**Comment by huypxgear** [comment] 2022-03-04 11:55
It is similar to my code right now. I have a dynamic config. The Flatpick config is based on the DateTime value and it is visible or not

**Comment by huypxgear** [comment] 2022-03-04 12:14
Here is another sample the display is not correct on weekday
https://codesandbox.io/s/great-bash-02s6p0?file=/src/components/HelloWorld.vue

**Comment by ankurk91** [comment] 2022-03-04 12:20
>It is similar to my code right now. I have multiple configs. The Flatpick config is based on the DateTime value format and the visible value

Sorry, I dont know about your project. and what are you trying to achieve,

You have shared a another but different example now, which one to follow ?

**Comment by ankurk91** [comment] 2022-03-04 12:24
Check this fork
https://codesandbox.io/s/icy-cloud-5t72n3?file=/src/components/HelloWorld.vue

I am supplying date like
```
start_date: new Date("03/05/2022 05:15:03"), // 5 march
```

and it is showing correct weekday for me,
FYI: I am using Ms Edge browser latest  version.

**Comment by huypxgear** [comment] 2022-03-04 12:37
@ankurk91 

>Sorry, I don't know about your project. and what are you trying to achieve,

I have multiple schedules. The date-time format in each schedule could be different. The schedule interface is hidden, it is visible when enable on UI. The flatpick config is based on the date-time schedule format. I don't want to calculate the flatpick config when the schedule component mounted. I want to do it only when the component is visible. Therefore I have created a visible value to detect it. When the component is visible I calculate the flatpick base on the date-time format and re-update the flatpickr config again. 

>You have shared a another but different example now, which one to follow ?
The second one is using the date-time format `l, H:i`. When I passing the date time value which weekday is Thursday but the flatpick display is Saturday instead of


Sorry for my English

**Comment by ankurk91** [comment] 2022-03-04 12:46
I am not interested in knowing your project requirements.

If you can narrow down your code and just keep the minimal, would save mine and your time.

**Comment by huypxgear** [comment] 2022-03-04 12:49
I think it already is minimal
The first issue is the config change and the display time is not correct
The second issue is the weekday is incorrect when passing string date-time value

**Comment by ankurk91** [comment] 2022-03-04 12:53
You are examining my patience today 😁
I can keep chatting with you like this and your issue won't solve.

I have already solved your 2nd issue, any comment on that? 
Thanks.

**Comment by ankurk91** [comment] 2022-03-05 06:19
>I need to pass full date time value instead of only weekday and hour. is it right?

yes, you need to pass a valid date to v-model

You suppose to store the full datetime in your database.

I am closing this issue since you could not help me to narrow down the issue.

**Closed by ankurk91** 2022-03-05 06:19 UTC
Labels: need-more-info

**Comment by yogithesymbian** [comment] 2022-10-12 06:00
i only know `dateFormat: 'Y-m-d h:m:i',`
could you gimme a reference to similar properties 
what i see in flat-picker use `altFormat: 'j F Y - h:m K',`
k as am pm , and i only know i as am pm . 
i think its different .
