### ISSUE TITLE
Flatpickr close on any click when on bootstrap-vue modal

### ISSUE THREAD

**Issue by devRoshan** [ankurk91/vue-flatpickr-component#76] opened 2018-04-19 07:40 UTC

**Comment by ankurk91** [comment] 2018-04-19 08:40
@devRoshan
Can you describe a little what issue you are facing?

**Comment by devRoshan** [comment] 2018-04-19 08:45
@ankurk91 Im using bootstrap vue modal <b-modal></b-modal> component and inside b-modal component, i used flatpickr, When i change month , the flatpickr component hides itself.

**Comment by ankurk91** [comment] 2018-04-19 09:46
@devRoshan
I believe you are using [vue-bootstrap](https://bootstrap-vue.js.org/docs/components/modal) modal.
My vue component has nothing to do with closing the flatpickr.
I am happy to debug if you can setup a jsfiddle .

I tried it in bootstrap 4 modal (without vue-bootstrap) and it works fine there.

![screen1](https://user-images.githubusercontent.com/6111524/38984479-66d33cc2-43e4-11e8-819e-c83686a0efbd.gif)

**Comment by ankurk91** [comment] 2018-04-22 04:10
Closing due to no activity.
Feel free to re-open

**Comment by vigorem** [comment] 2018-06-06 20:54
Hi,

I've had the same problem using bootstrap-vue which is really interfering with flatpickr's behaviour.

I reproduced the issue in [this fiddle](https://jsfiddle.net/9ehnvxt4/)

with the following config:

    config: {
       wrap: false, // set wrap to true only when using 'input-group'
       altFormat: 'j F, Y',
       altInput: true,
       dateFormat: "Y-m-d H:i:S",
       enableTime: true,
       time_24hr: true,
       weekNumbers: true,
       allowInput: true,
    }

The `static`option mentionned on other threads doesn't solve this.

<img src="https://media.giphy.com/media/ybTbk1LrRG3AefrAPU/giphy.gif">

A turnaround could be found in setting `weekNumbers` to false. 

I'm really wondering how to impeach vue-bootstrap to interfer with components.

Sébastien

**Comment by ankurk91** [comment] 2018-06-07 04:15
@vigorem 
Both of your fiddle worked fine for me.
Datepicker UI shows, i was able to select a date. it also updates v-model.
The only issue i noticed there was that when i select any date, datepicker closes without asking for time.
![screen1](https://user-images.githubusercontent.com/6111524/41077974-8447337a-6a37-11e8-9451-5a8c9b90b43e.gif)

I am on Mac OS v10.12, Chrome 67.

**Comment by vigorem** [comment] 2018-06-07 07:00
> The only issue i noticed there was that when i select any date, datepicker closes without asking for time.

Yes sorry, I should have been more specific. This is exactly the issue,  the picker closes immediatly without allowing to change time.

Regarding the minDate I have to admit I can not reproduce the issue. Tweaking my fiddle, I however found a little bug reproduced (without bootstrap-vue)[here](https://jsfiddle.net/r3ys2dbt/) : if you pick the same day but on a letter time, the dependent field won't reset.

<img src="https://media.giphy.com/media/cYWZ3XdMHJaYYPNZBY/giphy.gif">

I'm on Mac OS v.10.13.4, Chrome 66

**Comment by ankurk91** [comment] 2018-06-07 07:06
We are discussing two different issues here, right? If so please [create](https://github.com/ankurk91/vue-flatpickr-component/issues/new) another issue.
We should be discussing the bootstrap-vue modal issue here only.

Believe you are trying to create a start date and end date picker.
Can you please follow the example in this repo.

https://github.com/ankurk91/vue-flatpickr-component/blob/4bdd1b788704b9a814f6868051016a159a025c8b/examples/App.vue#L352-L357

**Comment by vigorem** [comment] 2018-06-07 07:08
Yes your right, my fault, it's a different issue. I will check with the code you shared and open a ticket if necessary.

**Comment by MaximeWillinger** [comment] 2018-06-08 09:11
This is a known issue of flatpickr https://github.com/flatpickr/flatpickr/issues/1241

As a temporary workaround, you can add this option:
```javascript
static: true
```

and keep bootstrap default behaviour using:

```css
.flatpickr-wrapper {
  display: block !important;
}
```

It solved the closing issue with [bootstrap-vue](https://github.com/bootstrap-vue/bootstrap-vue) modals for me.

**Comment by ankurk91** [comment] 2018-06-08 09:53
Closing; as it is an upstream issue .

**Closed by ankurk91** 2018-06-08 09:53 UTC

**Comment by tmoodley** [comment] 2019-08-26 13:56
I was having this issue in ie11.  The no-enforce-focus worked for me.  Thanks @zealot128

**Comment by bsienn** [comment] 2019-10-09 09:01
@ankurk91 I suggest to add zealot128 comments in the docs as a Note for people using bootstrap-vue modal.

**Comment by Att4ck3rS3cur1ty** [comment] 2020-01-30 17:40
In IE/Edge, I have a DatePicker (FlatPicker) inside b-modal and when the user clicked in the dropdown menu, it was empty and used to suddenly close. I've tried dozens of threads linked to this one, but only
`:no-enforce-focus='true'` suggested by @zealot128 worked. 

Dude, you're my hero! Thank you so much!
