### ISSUE TITLE
When clicking on the Time 12:00 appears but it is not updated until on Model until the time is changed by clicking. 

### ISSUE THREAD

**Issue by shishirraven** [ankurk91/vue-flatpickr-component#110] opened 2018-09-25 23:50 UTC
**I'm submitting a small bug
**Current behavior**

I am only using time picker. 
When I click the time automatically the placeholder changes from to 12:00. 
But the model is not updated to 12:00. Until I manually change 12:00 to something and change it back.

This causes the users to think that time is 12:00 but actually it is not updated on the vue model.  

**Expected behavior**

If the user clicks the to pick time. Then automatically the model should be updated. 
to 12:00. 

**Minimal reproduction of the problem with instructions**
You can quickly replicate this by opening following example. 
I am using chrome. 
https://jsfiddle.net/63kzdwLx/2863/
a. After running click on the Select a Date. 
b. Click outside the the input anywhere. 
c.  You will see 12:00 in the box. But the model will remain empty. 

Thanks for for creating a Vue version of flatpickr. Really Appreciated.

**Comment by ankurk91** [comment] 2018-09-26 02:27
Duplicate of 
https://github.com/ankurk91/vue-flatpickr-component/issues/109

**Closed by ankurk91** 2018-09-26 02:27 UTC
