### ISSUE TITLE
binding with :class prop

### ISSUE THREAD

**Issue by allaghi** [ankurk91/vue-flatpickr-component#128] opened 2019-01-24 17:55 UTC
Hi ,
I am trying to implement binding class with flatpickr and I couldn't . 
this is my code 
```html
<b-form-group label="Title Received" class="col-md-3">
                            <flat-pickr v-model="car.title_received" :config="dateConfig" :placeholder="!isIEMode ? 'Title Received' : null" :class="{'is-invalid':errors.title_received}"/>
                        <div v-if="errors.title_received" class="invalid-feedback">
                                {{errors.title_received[0]}}    
                        </div>    
                        </b-form-group>
```

**Comment by ankurk91** [comment] 2019-01-25 02:08
Duplicate of
https://github.com/ankurk91/vue-flatpickr-component/issues/104

**Comment by sevenmay** [comment] 2020-01-09 17:23
Is there any news regarding this issue?
Using "altInput" is crucial for me.
Thanks!

**Closed** 2020-10-08 02:00 UTC
