### ISSUE TITLE
Programmatically Open Picker

### ISSUE THREAD

**Issue by byronferguson** [ankurk91/vue-flatpickr-component#94] opened 2018-07-10 16:03 UTC
**I'm submitting a ...**  (check one with "x")
```
[ ] Bug report => search github for a similar issue or PR before submitting
[ X ] Feature request
[ ] Other, please describe
```

**Tell about your platform**
* flatPickr version : 4.x.x
* Vue.js version : 2.x.x
* Browser name and version : Chrome 67
* This package version : x.x.x

**Expected behavior**
Ability to open the picker programmatically using the base libraries `.open()` method provided on the object.

**Minimal reproduction of the problem with instructions**

**Comment by ankurk91** [comment] 2018-07-10 16:06
This feature already exists in parent library

https://flatpickr.js.org/instance-methods-properties-elements/

You can access flat picker instance via $refs on Vue component

**Comment by ankurk91** [comment] 2018-07-10 16:24
Duplicate of https://github.com/ankurk91/vue-flatpickr-component/issues/33

**Closed by ankurk91** 2018-07-10 16:24 UTC
