### ISSUE TITLE
Dynamic class property not applied

### ISSUE THREAD

**Issue by treagod** [ankurk91/vue-flatpickr-component#220] opened 2021-02-27 12:29 UTC
**I'm submitting a ...**  
```
[x] Bug report 
[ ] Feature request
[ ] Other, please describe
```

**Tell about your platform**
* flatPickr version : 4.6.6
* Vue.js version : 3.0.0
* Browser name and version : Firefox 84.0.2
* This package version : 9.0.2

**Current behavior**
When I add a dynamic class binding to the component, i.e.
```html
<flat-pickr
  v-model="startDate"
  :config="config"
  class="input"
  :class="dateError ? 'is-danger' : ''"
></flat-pickr>
```
The `:class` property won't be evaluated

**Expected behavior**
When I add a dynamic class binding to the component, i.e.
```html
<flat-pickr
  v-model="startDate"
  :config="config"
  class="input"
  :class="dateError ? 'is-danger' : ''"
></flat-pickr>
```
The `:class` property will be evaluated if `dateError` is true and the input element will have the class `is-danger`

**Minimal reproduction of the problem with instructions**
Pass following config to the flatpickr component

```html
<template>
  <flat-pickr
    v-model="startDate"
    :config="config"
    class="input"
    :class="dateError ? 'is-danger' : ''"
  ></flat-pickr>
</template>
<script>
import flatPickr from "vue-flatpickr-component";
import "flatpickr/dist/flatpickr.css";

export default {
  data() {
    return {
      startDate: null,
      dateError: true,
      config: {
        altFormat: "j M, Y H:i",
        enableTime: true,
        altInput: true,
        time_24hr: true,
      },
    }
  }
}
</script>
```

**Comment by ankurk91** [comment] 2021-02-27 15:40
duplicate of https://github.com/ankurk91/vue-flatpickr-component/issues/127

**Closed by ankurk91** 2021-02-27 15:40 UTC
