### ISSUE TITLE
set locale language global ?

### ISSUE THREAD

**Issue by carlos00027** [ankurk91/vue-flatpickr-component#192] opened 2020-07-27 02:36 UTC
**I'm submitting a ...**  (check one with "x")
```
[ ] Bug report => search github for a similar issue or PR before submitting
[ ] Feature request
[ ] Other, please describe
```
how set local language global ?

**Tell about your platform**
* flatPickr version : 4.x.x
* Vue.js version : 2.6.x
* Browser name and version : Chrome|Firefox|Safari x.x.x
* This package version : x.x.x

**Current behavior**

**Expected behavior**

**Minimal reproduction of the problem with instructions**

**Comment by ankurk91** [comment] 2020-07-27 03:29
duplicate of https://github.com/ankurk91/vue-flatpickr-component/issues/49

**Closed by ankurk91** 2020-07-27 03:29 UTC
