### ISSUE TITLE
Unable to type in year 'input' when flatpickr is inside bootstrap-vue modal

### ISSUE THREAD

**Issue by 3tew** [ankurk91/vue-flatpickr-component#219] opened 2021-02-20 15:13 UTC
**I'm submitting a ...**  (check one with "x")
```
[x] Bug report => search github for a similar issue or PR before submitting
[ ] Feature request
[ ] Other, please describe
```

**Tell about your platform**
* nuxt version: 2.14.0
* flatPickr version : 4.6.9
* Vue.js version : 2.x
* Browser name and version : Chrome|Firefox|Edge x.x.x
* This package version : 8.1.6

**Current behavior**

Normally my Flatpickr input is in a common component which can be used without problems but when the Flatpickr input which is in b-modal (Bootstrap-Vue Modal) has a problem it cannot type in the field (year, hour or minute). when add 'inline: true' to config the input field is can type.

**Expected behavior**

**Minimal reproduction of the problem with instructions**

**Comment by ankurk91** [comment] 2021-02-20 15:15
Heya, please create a minimal re-production on codesandbox.
https://codesandbox.io/s/vue

**Comment by 3tew** [comment] 2021-02-20 15:33
@ankurk91 
https://codesandbox.io/s/kind-lumiere-1dg4d

FYI
You can click on the button to open the modal. then try to click on Flatpickr input to bring it up. You will not be able to type into the input (year).

![image](https://user-images.githubusercontent.com/5137066/108600798-ad6ba380-73cb-11eb-8502-8d303cfe8d80.png)

**Comment by ankurk91** [comment] 2021-02-20 16:18
Thanks, I will check in my day.

**Comment by ankurk91** [comment] 2021-02-21 05:07
I could not figure out the issue.

**Comment by 3tew** [comment] 2021-02-21 08:49
@ankurk91 
When you click on the common Flatpickr input, you will be able to use it normally. (can be type)
![1](https://user-images.githubusercontent.com/5137066/108620075-0e42bc80-745c-11eb-9e19-00396d099757.PNG)


But when Flatpickr input is in Modal (Bootstrap-Vue Modal), it cannot print in the input.
![2](https://user-images.githubusercontent.com/5137066/108620078-126eda00-745c-11eb-90cd-90ea59f47811.PNG)

**Comment by ankurk91** [comment] 2021-02-21 10:53
Hey, I meant, 
i was able to reproduce the issue but could figure out why it is happening.😅

Sorry for confusion.
I may have to spent more time to debug.

**Comment by SoldierPePe** [comment] 2021-06-16 10:28
The problem is in tabindex in the bootstrap modal content tag you need to remove to fix it
to fix the problem add these lines to App.vue
```javascript
mounted() {
    this.$root.$on('bv::modal::shown', bvEvent => {
      bvEvent.vueTarget.$refs.content.attributes.removeNamedItem('tabindex')
    })
}
```
the attribute will be removed every time modal is opened

![image](https://user-images.githubusercontent.com/20547556/122202994-4441fb80-cea6-11eb-9e5e-00de16f5abda.png)

![image](https://user-images.githubusercontent.com/20547556/122203078-59b72580-cea6-11eb-80d7-b1c174e06593.png)

**Comment by ankurk91** [comment] 2021-07-09 04:16
Closing the issue, since it is not related to this component, and above solution worked well.

**Closed by ankurk91** 2021-07-09 04:16 UTC
Labels: help wanted
