### ISSUE TITLE
range plugin not supported

### ISSUE THREAD

**Issue by luis7fj** [ankurk91/vue-flatpickr-component#64] opened 2018-01-31 06:39 UTC
app.js:94674 TypeError: Cannot read property 'value' of null
    at createSecondInput (app.js:95613)
    at Object.onReady (app.js:95648)
    at triggerEvent (app.js:94521)
    at init (app.js:93038)
    at FlatpickrInstance (app.js:94655)
    at _flatpickr (app.js:94670)
    at new flatpickr (app.js:94693)
    at VueComponent.mounted (app.js:92269)
    at callHook (app.js:18740)
    at Object.insert (app.js:19935)

**Comment by ankurk91** [comment] 2018-01-31 09:29
Duplicate of
https://github.com/ankurk91/vue-flatpickr-component/issues/38

**Closed** 2018-01-31 09:29 UTC
