### ISSUE TITLE
using 2 time picker on same page open another time picker

### ISSUE THREAD

**Issue by agus24** [ankurk91/vue-flatpickr-component#245] opened 2022-01-25 10:27 UTC
**I'm submitting a ...** 

```
[x] Bug report
[ ] Feature request
[ ] Other, please describe
```

**Tell about your platform**

* flatPickr version : 9.0.5
* Vue.js version : 3.0
* Browser name and version : Chrome
* This package version : 9.0.5

**Current behavior**
using 2 time picker on same page open another time picker

**Expected behavior**
open only 1 time picker

**Minimal reproduction of the problem with instructions**
put 2 time picker with this config
```
time: {
            wrap:true,
            altInput:true,
            allowInput:true,
            enableTime: true,
            noCalendar: true
          }
```

then add 2 input with same config will cause this issue happen

https://user-images.githubusercontent.com/23353234/150959628-3319c9e6-93f0-47c2-bf87-8b24dfdd97a0.mov

**Comment by ankurk91** [comment] 2022-01-25 11:02
please share minimal reproduction code.

You can copy this fiddle
https://jsfiddle.net/nv5h7skL/3/

**Comment by ankurk91** [comment] 2022-01-26 07:40
Closing due to lack of info

**Closed by ankurk91** 2022-01-26 07:40 UTC
Labels: need-more-info
