### ISSUE TITLE
Time picker sets default value on the form input but no v-model value when clicked

### ISSUE THREAD

**Issue by gppam** [ankurk91/vue-flatpickr-component#123] opened 2018-12-07 09:07 UTC
**I'm submitting a ...**
```
[x] Bug report => search github for a similar issue or PR before submitting
[ ] Feature request
[ ] Other, please describe
```

**Tell about your platform**
* flatPickr version : 4.5.2
* Vue.js version : 3.0.5
* Browser name and version : Firefox 63.0.3
* This package version : 8.0.0

**Current behavior**

Time picker puts a default value (in my case 12:00) but no `v-model` equivalent value when it is clicked.

![model](https://user-images.githubusercontent.com/14272390/49637211-b61c6d00-fa3f-11e8-9ac8-1f59b39fe4d1.gif)

**Expected behavior**

If time picker form is clicked there should be no default value put on the form. Or immediately set the v-model to the default value when it's clicked.

**Minimal reproduction of the problem with instructions**
I only set my flatpickr config to this:
```js
enableTime: true,
noCalendar: true,
dateFormat: "U",
altInput: true,
altFormat: "h:i K",
```
And my flatpickr: 
```html
<flat-pickr v-model="myTime" class="input" placeholder="Time" :config="pickr.time"></flat-pickr>
```

https://jsfiddle.net/kqvhzxy2/2/

**Comment by ankurk91** [comment] 2018-12-07 10:15
It is flatpickr issue that it does not fire `update` event but update the DOM.

Check the fiddle
https://jsfiddle.net/kqvhzxy2/2/
Notice it does not fire change event unless user update the time.

**Comment by gppam** [comment] 2018-12-07 11:17
I found a not-so-long workaround for it by using the `@on-close` hook, though it doesn't solve the bug itself.
```
<flat-pickr v-model="date" :config="config" placeholder="Select a date" name="birthdate" @on-close="selectDate"></flat-pickr>

selectDate(arr, dateStr) {
   this.date = dateStr
}
```

**Comment by ankurk91** [comment] 2018-12-17 12:44
Duplicate of
https://github.com/ankurk91/vue-flatpickr-component/issues/109
https://github.com/ankurk91/vue-flatpickr-component/issues/110

**Closed by ankurk91** 2018-12-17 12:44 UTC
Labels: upstream-limitation

**Comment by asharghi** [comment] 2019-01-30 15:32
For anyone finding this. No need for a method. Just do:

<flat-pickr v-model="date" :config="config" @on-close="date = $event" />

**Comment by fobiasmog** [comment] 2019-04-06 19:55
Another issue solution is use `watch`
https://jsfiddle.net/zbrejkin/n84y65w0/13/
